<?php
include '../../util/validarPeticion.php';
include '../../util/validarSession.php';
include '../../query/PasajeroDao.php';
include '../../cripto/Cripto.php';

header('Content-Type: application/json');
$id = filter_input(INPUT_POST, 'id');
$nombre = filter_input(INPUT_POST, 'nombre');
$papellido = filter_input(INPUT_POST, 'papellido');
$mapellido = filter_input(INPUT_POST, 'mapellido');
$rut = filter_input(INPUT_POST, 'rut');
$nick = filter_input(INPUT_POST, 'nick');
$password = Cripto::encriptar(filter_input(INPUT_POST, 'password'));
$telefono = filter_input(INPUT_POST, 'telefono');
$celular = filter_input(INPUT_POST, 'celular');
$direccion = filter_input(INPUT_POST, 'direccion');
$punto = filter_input(INPUT_POST, 'punto');
$mail = filter_input(INPUT_POST, 'mail');
$cargo = filter_input(INPUT_POST, 'cargo');
$centro = filter_input(INPUT_POST, 'centro');
$empresa = filter_input(INPUT_POST, 'empresa');
$ruta = filter_input(INPUT_POST, 'ruta');
$pasajero = new Pasajero();
$pasajero->setId($id);
$pasajero->setRut($rut);
$pasajero->setNombre($nombre);
$pasajero->setPapellido($papellido);
$pasajero->setMapellido($mapellido);
$pasajero->setTelefono($telefono);
$pasajero->setCelular($celular);
$pasajero->setDireccion($direccion);
$pasajero->setPunto($punto);
$pasajero->setMail($mail);
$pasajero->setNick($nick);
$pasajero->setPassword($password);
$pasajero->setCargo($cargo);
$pasajero->setCentroCosto($centro);
$pasajero->setEmpresa($empresa);
$pasajero->setRuta($ruta);
$pasajeroDao = new PasajeroDao();
$pasajeroDao->modificarPasajero($pasajero);
echo "{\"pasajero_id\":\"".$pasajero->getId()."\"}";

