<?php
include '../../util/validarPeticion.php';
include '../../util/validarSession.php';
include '../../query/ConductorDao.php';
include '../../cripto/Cripto.php';
include '../../log/Log.php';

header('Content-Type: application/json');
$id =filter_input(INPUT_POST, 'id');
$nombre =filter_input(INPUT_POST, 'nombre');
$papellido =filter_input(INPUT_POST, 'papellido');
$mapellido =filter_input(INPUT_POST, 'mapellido');
$tipo =filter_input(INPUT_POST, 'tipo');
$rut =filter_input(INPUT_POST, 'rut');
$nick =filter_input(INPUT_POST, 'nick');
$password = base64_encode(Cripto::encriptar(filter_input(INPUT_POST, 'password')));
$telefono =filter_input(INPUT_POST, 'telefono');
$celular =filter_input(INPUT_POST, 'celular');
$direccion =filter_input(INPUT_POST, 'direccion');
$mail =filter_input(INPUT_POST, 'mail');
$tipoLicencia =filter_input(INPUT_POST, 'tipoLicencia');
$banco = filter_input(INPUT_POST, 'banco');
$ncuenta = filter_input(INPUT_POST, 'ncuenta');
$tcuenta = filter_input(INPUT_POST, 'tcuenta');
$vencLicencia = DateTime::createFromFormat('d/m/Y', filter_input(INPUT_POST, 'vlicencia'))->format('Y/m/d');
$nacimiento = DateTime::createFromFormat('d/m/Y',filter_input(INPUT_POST, 'nacimiento'))->format('Y/m/d');
$renta =filter_input(INPUT_POST, 'renta');
$contrato =filter_input(INPUT_POST, 'contrato');
$afp =filter_input(INPUT_POST, 'afp');
$isapre =filter_input(INPUT_POST, 'isapre');
$isapreAd =filter_input(INPUT_POST, 'isapread');
$mutual =filter_input(INPUT_POST, 'mutual');
$seguroInicio = DateTime::createFromFormat('d/m/Y',filter_input(INPUT_POST, 'seguroInicio'))->format('Y/m/d');
$descuento =filter_input(INPUT_POST, 'descuento');
$transportista = filter_input(INPUT_POST, 'transportista');
$imagen =filter_input(INPUT_POST, 'imagen');
$archivoContrato =filter_input(INPUT_POST, 'archivoContrato');
$conductor = new Conductor();
$conductor->setId($id);
$conductor->setNombre($nombre);
$conductor->setPapellido($papellido);
$conductor->setMapellido($mapellido);
$conductor->setTipo($tipo);
$conductor->setRut($rut);
$conductor->setNick($nick);
$conductor->setPassword($password);
$conductor->setTelefono($telefono);
$conductor->setCelular($celular);
$conductor->setDireccion($direccion);
$conductor->setMail($mail);
$conductor->setTipoLicencia($tipoLicencia);
$conductor->setBanco($banco);
$conductor->setNumeroCuenta($ncuenta);
$conductor->setTipoCuenta($tcuenta);
$conductor->setVencLicencia($vencLicencia);
$conductor->setNacimiento($nacimiento);
$conductor->setRenta($renta);
$conductor->setContrato($contrato);
$conductor->setAfp($afp);
$conductor->setIsapre($isapre);
$conductor->setIsapreAd($isapreAd);
$conductor->setMutual($mutual);
$conductor->setSeguroInicio($seguroInicio);
$conductor->setDescuento($descuento);
$conductor->setTransportista($transportista);
$conductor->setImagenAdjunta($imagen);
$conductor->setContratoAdjunto($archivoContrato);
$conductorDao = new ConductorDao();
$conductorDao->modificarConductor($conductor);
echo "{\"conductor_id\":\"".$conductor->getId()."\"}";
Log::write_log("MODCONDUCTOR: ".$conductor->toString(), 0);